import { CharacterGURPS, LootGURPS, StaticCharacterGURPS } from "@actor/index.ts"
import {
	AttributeBonus,
	ConditionalModifierBonus,
	ContainedWeightReduction,
	CostReduction,
	DRBonus,
	MoveBonus,
	ReactionBonus,
	SkillBonus,
	SkillPointBonus,
	SpellBonus,
	SpellPointBonus,
	WeaponBonus,
} from "@feature/index.ts"
import {
	ConditionGURPS,
	EffectGURPS,
	EquipmentContainerGURPS,
	EquipmentGURPS,
	EquipmentModifierContainerGURPS,
	EquipmentModifierGURPS,
	MeleeWeaponGURPS,
	NoteContainerGURPS,
	NoteGURPS,
	RangedWeaponGURPS,
	RitualMagicSpellGURPS,
	SkillContainerGURPS,
	SkillGURPS,
	SpellContainerGURPS,
	SpellGURPS,
	StaticItemGURPS,
	TechniqueGURPS,
	TraitContainerGURPS,
	TraitGURPS,
	TraitModifierContainerGURPS,
	TraitModifierGURPS,
} from "@item/index.ts"
import { ActorType, ItemType } from "@module/data/misc.ts"
import { feature } from "@util/enum/feature.ts"
import { SkillResolver } from "@util/resolvers.ts"

export const GURPSCONFIG = {
	skillDefaults: [] as SkillResolver[],

	Actor: {
		documentClasses: {
			[ActorType.Character]: CharacterGURPS,
			[ActorType.LegacyCharacter]: StaticCharacterGURPS,
			[ActorType.LegacyEnemy]: StaticCharacterGURPS,
			[ActorType.Loot]: LootGURPS,
		},
		allowedContents: {
			[ActorType.Character]: [
				ItemType.Trait,
				ItemType.TraitContainer,
				ItemType.TraitModifier,
				ItemType.Skill,
				ItemType.Technique,
				ItemType.SkillContainer,
				ItemType.Spell,
				ItemType.RitualMagicSpell,
				ItemType.SpellContainer,
				ItemType.Equipment,
				ItemType.EquipmentContainer,
				ItemType.EquipmentModifier,
				ItemType.Note,
				ItemType.NoteContainer,
				ItemType.Effect,
				ItemType.Condition,
			],
			[ActorType.LegacyCharacter]: [ItemType.LegacyEquipment],
			[ActorType.LegacyEnemy]: [ItemType.LegacyEquipment],
			[ActorType.Loot]: [ItemType.Equipment, ItemType.EquipmentContainer],
		},
	},

	Item: {
		documentClasses: {
			[ItemType.Trait]: TraitGURPS,
			[ItemType.TraitContainer]: TraitContainerGURPS,
			[ItemType.TraitModifier]: TraitModifierGURPS,
			[ItemType.TraitModifierContainer]: TraitModifierContainerGURPS,
			[ItemType.Skill]: SkillGURPS,
			[ItemType.Technique]: TechniqueGURPS,
			[ItemType.SkillContainer]: SkillContainerGURPS,
			[ItemType.Spell]: SpellGURPS,
			[ItemType.RitualMagicSpell]: RitualMagicSpellGURPS,
			[ItemType.SpellContainer]: SpellContainerGURPS,
			[ItemType.Equipment]: EquipmentGURPS,
			[ItemType.EquipmentContainer]: EquipmentContainerGURPS,
			[ItemType.EquipmentModifier]: EquipmentModifierGURPS,
			[ItemType.EquipmentModifierContainer]: EquipmentModifierContainerGURPS,
			[ItemType.Note]: NoteGURPS,
			[ItemType.NoteContainer]: NoteContainerGURPS,
			[ItemType.LegacyEquipment]: StaticItemGURPS,
			[ItemType.Effect]: EffectGURPS,
			[ItemType.Condition]: ConditionGURPS,
			[ItemType.MeleeWeapon]: MeleeWeaponGURPS,
			[ItemType.RangedWeapon]: RangedWeaponGURPS,
		},
	},

	Feature: {
		classes: {
			[feature.Type.AttributeBonus]: AttributeBonus,
			[feature.Type.ConditionalModifierBonus]: ConditionalModifierBonus,
			[feature.Type.DRBonus]: DRBonus,
			[feature.Type.ReactionBonus]: ReactionBonus,
			[feature.Type.SkillBonus]: SkillBonus,
			[feature.Type.SkillPointBonus]: SkillPointBonus,
			[feature.Type.SpellBonus]: SpellBonus,
			[feature.Type.SpellPointBonus]: SpellPointBonus,
			[feature.Type.WeaponBonus]: WeaponBonus,
			[feature.Type.WeaponAccBonus]: WeaponBonus,
			[feature.Type.WeaponScopeAccBonus]: WeaponBonus,
			[feature.Type.WeaponDRDivisorBonus]: WeaponBonus,
			[feature.Type.WeaponMinSTBonus]: WeaponBonus,
			[feature.Type.WeaponMinReachBonus]: WeaponBonus,
			[feature.Type.WeaponMaxReachBonus]: WeaponBonus,
			[feature.Type.WeaponHalfDamageRangeBonus]: WeaponBonus,
			[feature.Type.WeaponMinRangeBonus]: WeaponBonus,
			[feature.Type.WeaponMaxRangeBonus]: WeaponBonus,
			[feature.Type.WeaponRecoilBonus]: WeaponBonus,
			[feature.Type.WeaponBulkBonus]: WeaponBonus,
			[feature.Type.WeaponParryBonus]: WeaponBonus,
			[feature.Type.WeaponBlockBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode1ShotsBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode1SecondaryBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode2ShotsBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode2SecondaryBonus]: WeaponBonus,
			[feature.Type.WeaponNonChamberShotsBonus]: WeaponBonus,
			[feature.Type.WeaponChamberShotsBonus]: WeaponBonus,
			[feature.Type.WeaponShotDurationBonus]: WeaponBonus,
			[feature.Type.WeaponReloadTimeBonus]: WeaponBonus,
			[feature.Type.WeaponSwitch]: WeaponBonus,
			[feature.Type.CostReduction]: CostReduction,
			[feature.Type.ContainedWeightReduction]: ContainedWeightReduction,
			[feature.Type.MoveBonus]: MoveBonus,
		},
	},
}
