import { ActorType, CharacterGURPS, LootGURPS, StaticCharacterGURPS } from "@actor"
import {
	AttributeBonus,
	ConditionalModifierBonus,
	ContainedWeightReduction,
	CostReduction,
	DRBonus,
	MoveBonus,
	ReactionBonus,
	SkillBonus,
	SkillPointBonus,
	SpellBonus,
	SpellPointBonus,
	WeaponBonus,
} from "@feature/index.ts"
import {
	ConditionGURPS,
	EffectGURPS,
	EquipmentContainerGURPS,
	EquipmentGURPS,
	EquipmentModifierContainerGURPS,
	EquipmentModifierGURPS,
	MeleeWeaponGURPS,
	NoteContainerGURPS,
	NoteGURPS,
	RangedWeaponGURPS,
	RitualMagicSpellGURPS,
	SkillContainerGURPS,
	SkillGURPS,
	SpellContainerGURPS,
	SpellGURPS,
	StaticItemGURPS,
	TechniqueGURPS,
	TraitContainerGURPS,
	TraitGURPS,
	TraitModifierContainerGURPS,
	TraitModifierGURPS,
} from "@item/index.ts"
import { ItemType } from "@item/types.ts"
import {
	AttributePrereq,
	ContainedQuantityPrereq,
	ContainedWeightPrereq,
	EquippedEquipmentPrereq,
	PrereqList,
	SkillPrereq,
	SpellPrereq,
	TraitPrereq,
} from "@prereq"
import { feature } from "@util/enum/feature.ts"
import { prereq } from "@util/enum/prereq.ts"
import { SkillResolver } from "@util/resolvers.ts"

export const GURPSCONFIG = {
	skillDefaults: [] as SkillResolver[],

	Actor: {
		documentClasses: {
			[ActorType.Character]: CharacterGURPS,
			[ActorType.LegacyCharacter]: StaticCharacterGURPS,
			[ActorType.LegacyEnemy]: StaticCharacterGURPS,
			[ActorType.Loot]: LootGURPS,
		},
		allowedContents: {
			[ActorType.Character]: [
				ItemType.Trait,
				ItemType.TraitContainer,
				ItemType.TraitModifier,
				ItemType.Skill,
				ItemType.Technique,
				ItemType.SkillContainer,
				ItemType.Spell,
				ItemType.RitualMagicSpell,
				ItemType.SpellContainer,
				ItemType.Equipment,
				ItemType.EquipmentContainer,
				ItemType.EquipmentModifier,
				ItemType.Note,
				ItemType.NoteContainer,
				ItemType.Effect,
				ItemType.Condition,
			],
			[ActorType.LegacyCharacter]: [ItemType.LegacyEquipment],
			[ActorType.LegacyEnemy]: [ItemType.LegacyEquipment],
			[ActorType.Loot]: [ItemType.Equipment, ItemType.EquipmentContainer],
		},
	},

	Item: {
		documentClasses: {
			[ItemType.Trait]: TraitGURPS,
			[ItemType.TraitContainer]: TraitContainerGURPS,
			[ItemType.TraitModifier]: TraitModifierGURPS,
			[ItemType.TraitModifierContainer]: TraitModifierContainerGURPS,
			[ItemType.Skill]: SkillGURPS,
			[ItemType.Technique]: TechniqueGURPS,
			[ItemType.SkillContainer]: SkillContainerGURPS,
			[ItemType.Spell]: SpellGURPS,
			[ItemType.RitualMagicSpell]: RitualMagicSpellGURPS,
			[ItemType.SpellContainer]: SpellContainerGURPS,
			[ItemType.Equipment]: EquipmentGURPS,
			[ItemType.EquipmentContainer]: EquipmentContainerGURPS,
			[ItemType.EquipmentModifier]: EquipmentModifierGURPS,
			[ItemType.EquipmentModifierContainer]: EquipmentModifierContainerGURPS,
			[ItemType.Note]: NoteGURPS,
			[ItemType.NoteContainer]: NoteContainerGURPS,
			[ItemType.LegacyEquipment]: StaticItemGURPS,
			[ItemType.Effect]: EffectGURPS,
			[ItemType.Condition]: ConditionGURPS,
			[ItemType.MeleeWeapon]: MeleeWeaponGURPS,
			[ItemType.RangedWeapon]: RangedWeaponGURPS,
		},
		childTypes: {
			[ItemType.Trait]: [
				ItemType.TraitModifier,
				ItemType.TraitModifierContainer,
				ItemType.MeleeWeapon,
				ItemType.RangedWeapon,
			],
			[ItemType.TraitContainer]: [
				ItemType.Trait,
				ItemType.TraitContainer,
				ItemType.TraitModifier,
				ItemType.TraitModifierContainer,
				ItemType.MeleeWeapon,
				ItemType.RangedWeapon,
			],
			[ItemType.TraitModifier]: [],
			[ItemType.TraitModifierContainer]: [ItemType.TraitModifierContainer, ItemType.TraitModifier],
			[ItemType.Skill]: [ItemType.MeleeWeapon, ItemType.RangedWeapon],
			[ItemType.Technique]: [ItemType.MeleeWeapon, ItemType.RangedWeapon],
			[ItemType.SkillContainer]: [ItemType.Skill, ItemType.Technique, ItemType.SkillContainer],
			[ItemType.Spell]: [ItemType.MeleeWeapon, ItemType.RangedWeapon],
			[ItemType.RitualMagicSpell]: [ItemType.MeleeWeapon, ItemType.RangedWeapon],
			[ItemType.SpellContainer]: [ItemType.Spell, ItemType.RitualMagicSpell, ItemType.SpellContainer],
			[ItemType.Equipment]: [
				ItemType.EquipmentModifier,
				ItemType.EquipmentModifierContainer,
				ItemType.MeleeWeapon,
				ItemType.RangedWeapon,
			],
			[ItemType.EquipmentContainer]: [
				ItemType.Equipment,
				ItemType.EquipmentContainer,
				ItemType.EquipmentModifier,
				ItemType.EquipmentModifierContainer,
				ItemType.MeleeWeapon,
				ItemType.RangedWeapon,
			],
			[ItemType.EquipmentModifier]: [],
			[ItemType.EquipmentModifierContainer]: [ItemType.EquipmentModifier, ItemType.EquipmentModifierContainer],
			[ItemType.Note]: [],
			[ItemType.NoteContainer]: [ItemType.Note, ItemType.NoteContainer],
			[ItemType.LegacyEquipment]: [],
			[ItemType.Effect]: [],
			[ItemType.Condition]: [],
			[ItemType.MeleeWeapon]: [],
			[ItemType.RangedWeapon]: [],
		},
	},

	Feature: {
		classes: {
			[feature.Type.AttributeBonus]: AttributeBonus,
			[feature.Type.ConditionalModifierBonus]: ConditionalModifierBonus,
			[feature.Type.DRBonus]: DRBonus,
			[feature.Type.ReactionBonus]: ReactionBonus,
			[feature.Type.SkillBonus]: SkillBonus,
			[feature.Type.SkillPointBonus]: SkillPointBonus,
			[feature.Type.SpellBonus]: SpellBonus,
			[feature.Type.SpellPointBonus]: SpellPointBonus,
			[feature.Type.WeaponBonus]: WeaponBonus,
			[feature.Type.WeaponAccBonus]: WeaponBonus,
			[feature.Type.WeaponScopeAccBonus]: WeaponBonus,
			[feature.Type.WeaponDRDivisorBonus]: WeaponBonus,
			[feature.Type.WeaponMinSTBonus]: WeaponBonus,
			[feature.Type.WeaponMinReachBonus]: WeaponBonus,
			[feature.Type.WeaponMaxReachBonus]: WeaponBonus,
			[feature.Type.WeaponHalfDamageRangeBonus]: WeaponBonus,
			[feature.Type.WeaponMinRangeBonus]: WeaponBonus,
			[feature.Type.WeaponMaxRangeBonus]: WeaponBonus,
			[feature.Type.WeaponRecoilBonus]: WeaponBonus,
			[feature.Type.WeaponBulkBonus]: WeaponBonus,
			[feature.Type.WeaponParryBonus]: WeaponBonus,
			[feature.Type.WeaponBlockBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode1ShotsBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode1SecondaryBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode2ShotsBonus]: WeaponBonus,
			[feature.Type.WeaponRofMode2SecondaryBonus]: WeaponBonus,
			[feature.Type.WeaponNonChamberShotsBonus]: WeaponBonus,
			[feature.Type.WeaponChamberShotsBonus]: WeaponBonus,
			[feature.Type.WeaponShotDurationBonus]: WeaponBonus,
			[feature.Type.WeaponReloadTimeBonus]: WeaponBonus,
			[feature.Type.WeaponSwitch]: WeaponBonus,
			[feature.Type.CostReduction]: CostReduction,
			[feature.Type.ContainedWeightReduction]: ContainedWeightReduction,
			[feature.Type.MoveBonus]: MoveBonus,
		},
	},

	Prereq: {
		classes: {
			[prereq.Type.List]: PrereqList,
			[prereq.Type.Trait]: TraitPrereq,
			[prereq.Type.Attribute]: AttributePrereq,
			[prereq.Type.ContainedQuantity]: ContainedQuantityPrereq,
			[prereq.Type.ContainedWeight]: ContainedWeightPrereq,
			[prereq.Type.EquippedEquipment]: EquippedEquipmentPrereq,
			[prereq.Type.Skill]: SkillPrereq,
			[prereq.Type.Spell]: SpellPrereq,
		},
	},

	select: {
		cr_level: {},
		cr_adj: {},
		study: {},
		study_level: {},
		attribute: {},
		progression: {},
		numeric_criteria: {},
		numeric_criteria_strict: {},
		string_criteria: {},
		has: {},
		all: {},
		tmcost: {},
		emcost: {},
		emweight: {},
		wsel: {},
		skillsel: {},
		spellcmp: {},
		spellmatch: {},
		stlimit: {},
		stdmg: {},
		movelimit: {},
		feature: {},
		feature_strict: {},
		prereq: {},
		prereq_strict: {},
		difficulty: {},
		container: {},
		affects: {},
		percentage: {},
		maneuvers: {},
		postures: {},
		display: {},
		length_units: {},
		weight_units: {},
		move_override: {},
		wswitch: {},
		wswitch_value: {},
		color: {},
		effect_action: {},
		conditions: {},
	} as Record<string, Record<string, string>>,
}
